# -*- coding: utf-8 -*-
"""personalised fitness trackerproject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15oC55Wxu5hyt5P70xmdBi_ilz6bmw-8H
"""

# Importing necessary libraries
def calculate_bmi(weight, height):
    """Calculate BMI."""
    bmi = weight / (height ** 2)
    return round(bmi, 2)

def suggest_calories(age, gender, weight, height, activity_level):
    """Suggest calories intake based on activity level."""
    height_cm = height * 100  # Convert height  meters to centimeters
    if gender.lower() == 'male':
        bmr = 66 + (13.75 * weight) + (5 * height_cm) - (6.75 * age)
    elif gender.lower() == 'female':
        bmr = 655 + (9.56 * weight) + (1.85 * height_cm) - (4.68 * age)

    # Activity multipliers
    if activity_level == 'sedentary':
        calories = bmr * 1.2
    elif activity_level == 'active':
        calories = bmr * 1.55
    elif activity_level == 'very active':
        calories = bmr * 1.9
    return round(calories)

def suggest_protein_intake(weight, goal):
    """Suggest protein intake based on goal."""
    if goal == 'muscle gain':
        protein = weight * 2.2  # grams of protein
    elif goal == 'weight loss':
        protein = weight * 1.5  # grams of protein
    else:
        protein = weight * 1.8  # grams of protein
    return round(protein, 2)

def log_exercise(exercise_name, sets, reps):
    log = {
        "exercise": exercise_name,
        "sets": sets,
        "reps": reps
    }
    return log

# Main function
def main():
    print("Welcome to the Gym Tracker!")

    # Getting user details
    age = int(input("Enter your age: "))
    gender = input("Enter your gender (male/female): ")
    weight = float(input("Enter your weight (in kg): "))
    height = float(input("Enter your height (in meters): "))

    # Calculate BMI
    bmi = calculate_bmi(weight, height)
    print(f"Your BMI is: {bmi}")

    #  calories intake
    activity_level = input("Enter your activity level (sedentary/active/very active): ").lower()
    calories = suggest_calories(age, gender, weight, height, activity_level)
    print(f"Your suggested daily calorie intake is: {calories} kcal.")

    # protein intake
    goal = input("Enter your fitness goal (muscle gain/weight loss/maintain): ").lower()
    protein = suggest_protein_intake(weight, goal)
    print(f"Your suggested daily protein intake is: {protein} grams.")

    # Log exercises
    log_data = []
    while True:
        exercise_name = input("Enter the exercise name (or type 'done' to finish): ")
        if exercise_name.lower() == 'done':
            break
        sets = int(input(f"Enter the number of sets for {exercise_name}: "))
        reps = int(input(f"Enter the number of reps for each set of {exercise_name}: "))
        log = log_exercise(exercise_name, sets, reps)
        log_data.append(log)

    # Show exercise log
    print("\nExercise Log:")
    for entry in log_data:
        print(f"Exercise: {entry['exercise']} | Sets: {entry['sets']} | Reps: {entry['reps']}")

# Run the program
if __name__ == "__main__":
    main()

